import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { HeaderLayout } from "@/components/Header/Header";
import { Layout } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout style={{ minHeight: "100vh", background: "#fff" }}>
          <AntdRegistry>
            <HeaderLayout />
            {children}
          </AntdRegistry>
        </Layout>
      </body>
    </html>
  );
}
