import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { HeaderLayout } from "@/components/Header/Header";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import { ConfigLayout } from "@/components/ConfigLayout/ConfigLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigLayout>
          <Layout style={{ minHeight: "100vh" }}>
            <AntdRegistry>
              <HeaderLayout />
              <Content>{children}</Content>
            </AntdRegistry>
          </Layout>
        </ConfigLayout>
      </body>
    </html>
  );
}
